repositories {
	 mavenCentral()
	maven {
		name = 'Fabric'
		url = 'https://maven.fabricmc.net/'
	}
}

dependencies {
	compileOnly 'org.ow2.asm:asm:9.8'
	compileOnly 'org.ow2.asm:asm-commons:9.8'
	compileOnly 'net.fabricmc:stitch:0.6.2'
	compileOnly 'net.fabricmc:tiny-mappings-parser:0.3.0+build.17'
}
