name: Java CI with Gradle

on:
  push:
    branches: [ 1.21.11 ]
  pull_request:
    branches: [ 1.21.11 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21 compiler
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Remember JDK 21
        run: echo "JAVA21_HOME=$JAVA_HOME" >> "$GITHUB_ENV"
      - name: Set up JDK 17 for Gradle
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --stacktrace --info
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Optifabric-Artifact
          path: build/libs/optifabric-*.*.jar
          if-no-files-found: error
